// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCWJ1IGPCFg8fR4xK9D1SbkBzsoZZzE_wk",
      authDomain: "finance-tracker-4b7f8.firebaseapp.com",
      projectId: "finance-tracker-4b7f8",
      storageBucket: "finance-tracker-4b7f8.firebasestorage.app",
      messagingSenderId: "484722509286",
      appId: "1:484722509286:web:f5f8b3260522b2c9648227",
      measurementId: "G-PJVZRKNCNB");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZmEVTUlO3VDEiOk4XjFrxVPKN7qsaes',
    appId: '1:484722509286:android:9b4d5714a2f51ca0648227',
    messagingSenderId: '484722509286',
    projectId: 'finance-tracker-4b7f8',
    storageBucket: 'finance-tracker-4b7f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUcHHrK1PWld6ldZ95Bf41KH8VP9FPVfo',
    appId: '1:484722509286:ios:a5d9b49ef95a7f7d648227',
    messagingSenderId: '484722509286',
    projectId: 'finance-tracker-4b7f8',
    storageBucket: 'finance-tracker-4b7f8.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUcHHrK1PWld6ldZ95Bf41KH8VP9FPVfo',
    appId: '1:484722509286:ios:a5d9b49ef95a7f7d648227',
    messagingSenderId: '484722509286',
    projectId: 'finance-tracker-4b7f8',
    storageBucket: 'finance-tracker-4b7f8.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJ1IGPCFg8fR4xK9D1SbkBzsoZZzE_wk',
    appId: '1:484722509286:web:701663114b0901f0648227',
    messagingSenderId: '484722509286',
    projectId: 'finance-tracker-4b7f8',
    authDomain: 'finance-tracker-4b7f8.firebaseapp.com',
    storageBucket: 'finance-tracker-4b7f8.firebasestorage.app',
    measurementId: 'G-3580XX07KZ',
  );
}
